
development:
  adapter: mysql2
  database: jobsite_development
  username: root
  password: html8888
  host: localhost

test:
  adapter: mysql2
  database: jobsite_test
  username: root
  password: html8888
  host: localhost

production:
  adapter: mysql2
  database: jobsite_production
  username: root
  password: html8888
  host: localhost
